### ISSUE TITLE
auto-checkout of website on provision

### ISSUE THREAD

**Issue by easterncoder** [irmec/vagrant#1]
I suggest that we auto-checkout the website to `/vagrant/git-projects/irmec-website` on 

Then modify `vhosts.conf` to match. This way, we don't have to worry about syncs since `/vagrant/` in the guest is accessible in the host as well.

Thoughts?

**Comment by slick2** [comment]
yeah that's a good idea on which we can do git-projects/irmec-website as a sub repo

then changed the ansible apache.yaml on the doc root and vhost

**Comment by slick2** [comment]
made a provision for apache we just need to change to host file of the host machine.  when cloning this repo i've added the irmec-website repo as submodule.
